# $$Pandas$$

- Pandas is a python library --- `Panel Data`
- that makes working with tabular data easy
- provides fast, flexible, and expressive data structures designed to make working with tables easy
- Tabular data with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet
- [Documentation](https://pandas.pydata.org/docs/getting_started/overview.html)
- 
- Data Structures in pandas are:

Dimensions | Name | Description
----|---|---
1 | Series  | 1D   labeled homogeneously-typed array
2 | DataFrame | General 2D   labeled, size-mutable tabular structure with potentially heterogeneously-typed column

![](https://pandas.pydata.org/docs/_images/01_table_dataframe.svg)

- main purpose is commonly ---> data prepration / data pre-processing
- You can explore, clean, and transform data before analytics or building ML Models
- 
-  we can :
    - Read from csv files
    - select rows and columns
    - filter, sort, group data
    - handle missing values
    - prepare data for analytics or ML

In [2]:
# pip install pandas

In [3]:
# creating a series object

import numpy as np
import pandas as pd

data = np.arange(1,10)* 10
type(data) # array

series_a = pd.Series(data, name= "data")
print(series_a)
# you will observe index has been added

type(series_a)

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
Name: data, dtype: int64

pandas.Series

In [4]:
dataframe_a = pd.DataFrame(data) # dataframe of a single column

# we combined a lot of series objects together
dataframe_a = pd.DataFrame([series_a,series_a,series_a,series_a]) # the name will turn to label
dataframe_a

# Transpose a Data Frame
pd.DataFrame([series_a, series_a, series_a, series_a]).T

   data  data  data  data
0    10    10    10    10
1    20    20    20    20
2    30    30    30    30
3    40    40    40    40
4    50    50    50    50
5    60    60    60    60
6    70    70    70    70
7    80    80    80    80
8    90    90    90    90

#### Data structures
- SERIES:
    - INDEX ---> number assigned to each row
    - No label---> assigned to columns
    - Name - can have a series name

- DATAFRAME:
    - LABEL ---> column name --- By default it will serially done ---
        - starts from 0 
    - INDEX ---> number for each row
    - 
- Create:
    - using lists, arrays, dictionaries, list of dictionaries
    - use structured data to create dataframes
        - rreading a csv file, or an SQL file, or any spreadsheet .xslx

### Methods to create DF

In [5]:
# Dictionary to create a dataframe
# Every key becomes a column
data = {
    "student": ["aqilah","Nazihah","Alia"],
    "maths": [88, 92, 85],
    "science": [95,96,98],
    "physics": [68, 78, 61]
}

marks_df = pd.DataFrame(data)
marks_df

   student  maths  science  physics
0   aqilah     88       95       68
1  Nazihah     92       96       78
2     Alia     85       98       61

#### Exercise
1. Create a `pd.Series` with 5 temperature values and print it.
2. Create a pd.DataFrame with columns "`City`" and "`Temperature`" for 3 cities.
3. Check the `type()` of each object you created.
4. Add a name to your Series and print it again.

In [6]:
# city's temperature
city_temps = {
    "City": ["Kuala Lumpur", "Leipzig", "Kashmir", "London", "Tokyo"],
    "Temperature": [31, 7, 10, 23, 25]
}

# lists are flexible
# we can miss a key value pair
# this results in Missing values
city_temps = [
    {"city": "Kuala Lumpur", "Temperature":31},
    {"city": "Leipzig", "Temperature":7},
    {"city": "Kashmir", "Temperature":10},
    {"city": "London", "Temperature":23},
    {"city": "Tokyo"},
    {"city": "Helsiki" , "Temperature": None}
]
 
temp_df = pd.DataFrame(city_temps)
temp_df

           city  Temperature
0  Kuala Lumpur         31.0
1       Leipzig          7.0
2       Kashmir         10.0
3        London         23.0
4         Tokyo          NaN
5       Helsiki          NaN

#### Nan Values
- Not a Number
- Missing Values - 
    - np.nan in a dataframe
    - or we can also have None type data in a dataframe
- A database takes all the entries of a form at once
    - list of dictionaries is more suitable
    - in this situation, sometimes a key value pair can go missing 
    - or not reach the database
- other situations:
    - sensor errors
    - incomplete form submissions 
    -

#### Reading from CSV file
- CSV - Comma Separated Values
- Let's download a csv file from here [>>>> Link...](https://github.com/yannie28/Global-Superstore/blob/master/Global_Superstore(CSV).csv)
-

In [1]:
path = r"C:\Users\devid\Desktop\Nexperts Academy\AIML-nexperts4\Resources\Global_Superstore(CSV).csv"
df_sales = pd.read_csv(path)
df_sales.head(2)

NameError: name 'pd' is not defined

In [ ]:
# we created ourselves
marks_df

# Export a dataframe too
marks_df.to_csv("marks.csv", index = False)

We now have the DATAFRAMES

### Basic Exploration Methods in Pandas
- to explore data/ dataframes
- 

- some methods that can be used on DataFrames
    - `df.head()` - first 5 records/rows
    - `df.tail` - ending 5
    - `df.sample()` - random entry from df
    - pass in the argument for how many records you want
    - `df.info()` - basic information about df
    - `df.describe()` - statistical information about the df

- .shape
- .dtypes
- .columns
- .size

In [9]:
marks_df.head()
marks_df.tail()
marks_df.sample()

  student  maths  science  physics
0  aqilah     88       95       68

In [10]:
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          1000 non-null   int64
 1   Order ID        1000 non-null   str
 2   Order Date      1000 non-null   str
 3   Ship Date       1000 non-null   str
 4   Ship Mode       1000 non-null   str
 5   Customer ID     1000 non-null   str
 6   Customer Name   1000 non-null   str
 7   Segment         1000 non-null   str
 8   Postal Code     194 non-null    float64
 9   City            1000 non-null   str
 10  State           1000 non-null   str
 11  Country         1000 non-null   str
 12  Region          1000 non-null   str
 13  Market          1000 non-null   str
 14  Product ID      1000 non-null   str
 15  Category        1000 non-null   str
 16  Sub-Category    1000 non-null   str
 17  Product Name    1000 non-null   str
 18  Sales           1000 non-null   float64
 19  Quantity        1000 non-null   int64
 20  Discount        1000 non-null   float64
 21  Profit          1000 non-null   float64
 22  Shipping Cost   1000 non-null   float64
 23  Order Priority  1000 non-null   str
dtypes: float64(5), int64(2), str(17)
memory usage: 187.6 KB

In [11]:
df_sales.describe() # only for the numerical columns
# to check the statistics
#

,Row ID,Postal Code,Sales,Quantity,Discount,Profit,Shipping Cost
count,1000.000000,194.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,25079.328000,53966.170103,1710.971470,5.55800,0.092840,288.920440,272.384897
std,12897.726632,33734.306466,1259.239238,2.71846,0.148666,574.504782,176.160716
min,58.000000,2920.000000,1.910000,1.00000,0.000000,-3059.820000,1.070000
25%,15118.750000,19134.000000,826.907500,4.00000,0.000000,10.037500,209.827500
50%,25084.500000,60564.000000,1585.115000,5.00000,0.000000,190.685000,258.897500
75%,34524.000000,88187.500000,2477.812500,7.00000,0.150000,518.872500,351.070250
max,51284.000000,98198.000000,9892.740000,14.00000,0.800000,4946.370000,923.630000

In [12]:
# can implement these methods on series too
df_sales.Quantity
df_sales['Quantity'].describe()

count    1000.00000
mean        5.55800
std         2.71846
min         1.00000
25%         4.00000
50%         5.00000
75%         7.00000
max        14.00000
Name: Quantity, dtype: float64

## Basic data ACCESSING in a dataframe

- SELECTION methods
- access a single column --- using `[]` or `.` operator
    - `df['column_name']` ---> Return a series object
    - show the `name` and the `data type` as well
    - 
- accessing multiple columns ---> 
    - `df[[col1, col2, col3]]` ---> specific columns
- access a value in a column
    - `df['column_name'][index_value]` ---> gets to a particular value

- access a new column, that does not exist, it creates a new column
    - df['new_column_name'] = # define what goes into the column

- using loc and iloc

In [ ]:
# getting a single column --- or value

temp_df['city'][5] # accessing a single value
type(temp_df['city'][5]) # the type is nan
type(temp_df['Temperature'][5]) # Nan values in dataframes are empty numpy values

temp_df.Temperature

0    31.0
1     7.0
2    10.0
3    23.0
4     NaN
5     NaN
Name: Temperature, dtype: float64

In [ ]:
df_sales.head(1) # single top row

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11/11/2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.77,High

In [ ]:
# accessing indexes in array
a = np.array([100,200,300,400,500])

a[1]

a[   [3,2,4,1]   ]

array([400, 300, 500, 200])

In [ ]:
# accessing columns in df
cols = ["Category", "Sub-Category","Sales", "Profit"]
df_sales[cols]

            Category Sub-Category    Sales  Profit
0         Technology       Phones   221.98   62.15
1          Furniture       Chairs  3709.40 -288.77
2         Technology       Phones  5175.17  919.97
3         Technology       Phones  2892.51  -96.54
4         Technology      Copiers  2832.96  311.52
..               ...          ...      ...     ...
995        Furniture       Tables  2614.69 -821.96
996  Office Supplies   Appliances    69.48   20.84
997       Technology      Copiers   636.78  286.50
998        Furniture    Bookcases  2751.20  110.00
999       Technology       Phones  1587.00  -76.56

[1000 rows x 4 columns]

#### Using .iloc and .loc

- iloc - integer location 
    - df.iloc[Row_index] - select row of a certain index
    - df.iloc[start_Row : end_Row: Stepsize] - selects multiple rows - from start to end
    - 
    - can index too ---  range of rows, range columns
    - df.iloc[row_index , column index]
    - df.iloc[`row_index_start:row_index_end: Stepsize` , `col_index_start:col_index_end: Stepsize`]
    -

In [ ]:
df_sales.iloc[:5] # first 5 rows
df_sales.iloc[:5 , :5] # first 5 rows, columns
df_sales.iloc[:5 , 3:15]
df_sales.iloc[:2 , [2,3,4,6,7,8,9,10,11,12,13,15]]


# to select certain columns
df_sales.columns

cols = ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority']

# manually
useful_cols = [ 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority']

df_sales[cols] # or useful_cols

# professionally there are other ways to choose columns
# create a list of e.g. numeric columns, by running for loop over all the columns


# data cleaning
# string_cols = [col for col in cols if df_sales[cols].dtype == 'str'] # need to fix this

> #### .loc

- .loc
- focuses on label of index--- can be text 
- NAMES matter --- Not the numbers
-

In [121]:
temp_df.loc[1] # returns a row --- as a series object

temp_df.loc[0:3] # works return first three rows

# temp_df.loc[0:3, [0,1]] # wont' work
# temp_df.loc[0:3, 0:2] # wont' work

temp_df.loc[0:3, ['city', 'Temperature']] # works--- we are writing the labels this time

           city  Temperature
0  Kuala Lumpur         31.0
1       Leipzig          7.0
2       Kashmir         10.0
3        London         23.0

In [123]:
# create a dictionary -- with string indexes
city_temps = [
    {"city": "Kuala Lumpur", "Temperature":31},
    {"city": "Leipzig", "Temperature":7},
    {"city": "Kashmir", "Temperature":10},
    {"city": "London", "Temperature":23},
    {"city": "Tokyo"},
    {"city": "Helsiki" , "Temperature": None}
]
 
temp_df = pd.DataFrame(city_temps, index= ['city1','city2','city3','city4','city5', 'city6'])
temp_df

               city  Temperature
city1  Kuala Lumpur         31.0
city2       Leipzig          7.0
city3       Kashmir         10.0
city4        London         23.0
city5         Tokyo          NaN
city6       Helsiki          NaN

In [133]:
temp_df.loc[['city6','city5','city4'], ['Temperature']]

       Temperature
city6          NaN
city5          NaN
city4         23.0

> What is the difference between iloc and loc in your own words

---

##### Common Methods in Pandas

- some methods that can be used on DataFrames
    - .shape
    - .dtypes
    - .columns
    - .size

-

In [ ]:
df_sales.shape # (1000, 24) --- rows, columns
df_sales.dtypes # returns datatype of all each column
# int64, float64, str, 
df_sales.City.dtypes # for type check of single column

df_sales.columns # an array of columns --- pandas.Index type
df_sales.size # 24 * 1000, total elements

24000

##### Data types inside of DataFrames in Python
- often times we require to select a certain type of columns in Python
- 
- There are five main dtypes in pandas:
    - `object`: Text or mixed numeric values
    - `bool`: True or False values
    - `int64`: Integer values
    - `float64`: Floating point values
    - `datetime64`: Date and time values

In [18]:
data = {
    'Name': ['Kate' , 'Christy', 'Tommy'],
    'Memberhip': [True, True, False],
    'Quantity': [5,4,1],
    'Sales': [52.50, 42.00, 10.50],
    'Date': pd.to_datetime(['2026-01-21', '2026-01-26', '2026-01-27']),
    'Serial': ['F101','F102', 100 ]
}


df_sample = pd.DataFrame(data)
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       3 non-null      str
 1   Memberhip  3 non-null      bool
 2   Quantity   3 non-null      int64
 3   Sales      3 non-null      float64
 4   Date       3 non-null      datetime64[us]
 5   Serial     3 non-null      object
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), object(1), str(1)
memory usage: 255.0+ bytes

### Creating and dropping columns

In [135]:
# access a column that does not exist, and it will be created
df_sample['idrees'] = df_sample.Sales / 2 # calculated column
df_sample

      Name  Memberhip  Quantity  Sales       Date Serial       Days  idrees
2    Tommy      False         1   10.5 2026-01-27    100    Tuesday    5.25
1  Christy       True         4   42.0 2026-01-26   F102     Monday   21.00
0     Kate       True         5   52.5 2026-01-21   F101  Wednesday   26.25

In [136]:
# Delete a column
df_sample.drop('idrees', axis = 1, 
                inplace = True # modifies the dataset. Otherwise change will not occur
)

# delete a row
df_sample.drop(1, axis = 0, 
                inplace = True # modifies the dataset. Otherwise change will not occur
)

In [137]:
df_sample

    Name  Memberhip  Quantity  Sales       Date Serial       Days
2  Tommy      False         1   10.5 2026-01-27    100    Tuesday
0   Kate       True         5   52.5 2026-01-21   F101  Wednesday

- Copy vs View

    - generally all variables are safe when accessing partial dataframes
    - but in need, we can create multiple copies as well using `.copy()`

In [ ]:
# copy vs view exists here too

# copy created
newdf = df_sample[['Name','Memberhip','Quantity']].copy()

# changing the copy
newdf['idrees'] = [1,2,3]
newdf

      Name  Memberhip  Quantity  idrees
0     Kate       True         5       1
1  Christy       True         4       2
2    Tommy      False         1       3

In [23]:
# original did not get this change
df_sample

# change in orignial
df_sample['Days'] = df_sample.Date.dt.day_name()
df_sample

# the copy stays as it was
# newdf

      Name  Memberhip  Quantity  Sales       Date Serial       Days
0     Kate       True         5   52.5 2026-01-21   F101  Wednesday
1  Christy       True         4   42.0 2026-01-26   F102     Monday
2    Tommy      False         1   10.5 2026-01-27    100    Tuesday

In [24]:
# Let's test a view
# if a view is created changing it, should change the original

# create a view ---> Subset of the original data
sampleview = df_sample.iloc[0:3]
sampleview

# make a change in sample viewww
sampleview['Quantity'] = [0,0,0]
sampleview

# no change in original
df_sample

      Name  Memberhip  Quantity  Sales       Date Serial       Days
0     Kate       True         5   52.5 2026-01-21   F101  Wednesday
1  Christy       True         4   42.0 2026-01-26   F102     Monday
2    Tommy      False         1   10.5 2026-01-27    100    Tuesday

#### Methods for Data Analysis
- .sort_values() - by a particular column sort values and thus all the rows accordingly
- .sort_index() - sort using the index, ascending/decending
- .value_counts() - frequency of values in a dataframe
- .unique() - return list of unique values in a column
- .duplicated() - return to you if there is a duplicate record
- .isna() or .isnull() - return True for values that are NaN
-

In [25]:
df_sample.sort_values(by= "Quantity", ascending= True, inplace= True)

In [26]:
df_sample.sort_index(ascending= False) # by index

      Name  Memberhip  Quantity  Sales       Date Serial       Days
2    Tommy      False         1   10.5 2026-01-27    100    Tuesday
1  Christy       True         4   42.0 2026-01-26   F102     Monday
0     Kate       True         5   52.5 2026-01-21   F101  Wednesday

In [139]:
df_sample.value_counts()

Name   Memberhip  Quantity  Sales  Date        Serial  Days
Tommy  False      1         10.5   2026-01-27  100     Tuesday      1
Kate   True       5         52.5   2026-01-21  F101    Wednesday    1
Name: count, dtype: int64

In [ ]:
df_sales.Country.value_counts()
df_sales.City.value_counts()
df_sales['Sub-Category'].value_counts()

Country
United States    194
Australia         85
France            76
China             75
India             64
                ...
Benin              1
Bolivia            1
Chile              1
Martinique         1
Syria              1
Name: count, Length: 93, dtype: int64

In [ ]:
df_sales['Sub-Category'].unique() # how many unique values exists in sub categories
df_sales.Country.unique()

<StringArray>
[                   'United States',                        'Australia',
                          'Germany',                          'Senegal',
                      'New Zealand',                      'Afghanistan',
                     'Saudi Arabia',                           'Brazil',
                            'China',                           'France',
                            'Italy',                         'Tanzania',
                           'Poland',                   'United Kingdom',
                           'Mexico',                      'El Salvador',
                           'Taiwan',                            'India',
               'Dominican Republic', 'Democratic Republic of the Congo',
                        'Indonesia',                          'Uruguay',
                             'Iran',                       'Mozambique',
                       'Bangladesh',                            'Spain',
                          'Ukraine',                        'Nicaragua',
                          'Morocco',                      'Philippines',
                          'Austria',                         'Colombia',
                      'Netherlands',                         'Malaysia',
                          'Ecuador',                         'Thailand',
                          'Somalia',                        'Guatemala',
                          'Belarus',                         'Cambodia',
                     'South Africa',                           'Canada',
                            'Japan',                           'Russia',
                            'Egypt',                       'Azerbaijan',
                        'Lithuania',                        'Argentina',
                          'Lesotho',                          'Vietnam',
                             'Cuba',                          'Romania',
                           'Turkey',                         'Cameroon',
                          'Hungary',                        'Singapore',
                           'Angola',                          'Belgium',
                         'Pakistan',                          'Finland',
                            'Ghana',                           'Zambia',
                             'Iraq',                          'Liberia',
                          'Georgia',                      'Switzerland',
                          'Albania',                             'Chad',
                       'Montenegro',                          'Namibia',
                         'Portugal',                       'Madagascar',
                           'Sweden',                  'Myanmar (Burma)',
                          'Jamaica',                           'Greece',
                            'Qatar',            'Republic of the Congo',
                           'Norway',                          'Algeria',
                      'South Korea',                          'Nigeria',
                          'Estonia',                    'Cote d'Ivoire',
                         'Honduras',                         'Paraguay',
                   'Czech Republic',         'Central African Republic',
                            'Benin',                          'Bolivia',
                            'Chile',                       'Martinique',
                            'Syria']
Length: 93, dtype: str

In [30]:
df_sales['Ship Mode'].duplicated()

0      False
1      False
2       True
3       True
4      False
       ...
995     True
996     True
997     True
998     True
999     True
Name: Ship Mode, Length: 1000, dtype: bool

In [31]:
df_sales.isna()
df_sales.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

### Aggregations
- sum(), mean, min, max
- .count() - give all the times values exists
- .value_counts() - number of times each row exists --- makes sense for categories
-

In [57]:
df_sales.sum()
df_sales.Quantity.sum()

df_sales.Profit.mean()

df_sales.Profit.min()
df_sales.Profit.max()

df_sales[["Quantity", "Profit", "Shipping Cost"]].sum()

df_sales[["Quantity", "Profit", "Shipping Cost"]].count()

# all at same time
df_sales.Quantity.agg(['mean','max','min', 'count', 'sum', 'std', 'var','prod'])

df_sales[["Sub-Category", "City", "Segment"]].value_counts()

Sub-Category  City           Segment
Binders       New York City  Consumer       5
Phones        London         Consumer       3
Copiers       Sydney         Corporate      3
Binders       New York City  Home Office    3
Paper         New York City  Home Office    3
                                           ..
Phones        Homs           Corporate      1
Tables        Liaoyang       Consumer       1
Appliances    San Francisco  Corporate      1
Copiers       Taupo          Consumer       1
Bookcases     Araguaína      Corporate      1
Name: count, Length: 934, dtype: int64

## Filtering, Grouping 
- 
- Filtering - we keep only the rows, we care about
    - eg. students whose marks in maths were greater than 90
    -

In [33]:
a = np.array(range(10))
a =  np.arange(10)

# Boolean Masking in Numpy

# create array b using a, with only numbers greater than 5
b = a[(a>5) & (a<8)] # BOTH conditions true --- intersection --- AND
b = a[(a>5) | (a<8)] # Either of the conditions is true
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# i want a dataframe in which the quantity is greater than 5

mask = df_sales['Quantity'] > 5
mid_quantity = df_sales[mask]
mid_quantity.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2014-JR162107-41675,2/5/2014,2/7/2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.49,Medium
4,47221,SG-2014-RH9495111-41948,11/5/2014,11/6/2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.04,Critical
7,31192,IN-2013-MB1808592-41378,4/14/2013,4/18/2013,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.84,6,0.0,996.48,878.38,High
13,4132,MX-2013-VF2171518-41591,11/13/2013,11/13/2013,Same Day,VF-2171518,Vicky Freymann,Home Office,NaN,Toledo,...,FUR-CH-4530,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",2221.80,7,0.0,622.02,810.25,Critical

In [77]:
# Exercise: Only get the data for Toledo City from df_sales

df_city_Toledo = df_sales[ df_sales['City'] == 'Toledo']
df_city_Toledo

df_Segment_HO = df_sales[ df_sales['Segment'] == 'Home Office']
df_Segment_HO.sort_index().head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.160,Medium
13,4132,MX-2013-VF2171518-41591,11/13/2013,11/13/2013,Same Day,VF-2171518,Vicky Freymann,Home Office,NaN,Toledo,...,FUR-CH-4530,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",2221.80,7,0.0,622.02,810.250,Critical
23,13528,ES-2014-LB16795139-41697,2/27/2014,3/1/2014,Second Class,LB-16795139,Laurel Beltran,Home Office,NaN,Edinburgh,...,OFF-AP-4960,Office Supplies,Appliances,"KitchenAid Refrigerator, Black",5273.70,10,0.0,1898.40,730.910,High
41,29272,IN-2015-BF1100558-42319,11/11/2015,11/15/2015,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,TEC-PH-5269,Technology,Phones,"Motorola Smart Phone, with Caller ID",4518.78,7,0.0,632.52,658.690,High
68,8029,MX-2015-EM1420082-42328,11/20/2015,11/20/2015,Same Day,EM-1420082,Evan Minnotte,Home Office,NaN,Gómez Palacio,...,TEC-PH-5839,Technology,Phones,"Samsung Smart Phone, Cordless",1704.00,4,0.0,119.28,592.726,Critical

- Grouping:
    - df.groupby('category)[col1,col2,col3] . aggregation()

    - first you categorize ---- what colums to view --- then aggregate
        - different categories --- different columns --- diff aggregates
            - eg. by city --- Profit, Sales,  --- aggregate sum
                - city 1 -  456 | 5 | 
                - city 2 -  234 | 3 | 
                - city 3 -  4546| 12| 
                - ...

In [76]:
df_sales.groupby('City')['Profit'].sum()

# you can check how many times phones or other things were sold
df_sales.groupby('Sub-Category')['Sub-Category'].count()

Sub-Category
Accessories     38
Appliances     125
Art             18
Binders         38
Bookcases      130
Chairs          95
Copiers        126
Envelopes        2
Fasteners        6
Furnishings     14
Labels           6
Machines        52
Paper           32
Phones         179
Storage         45
Supplies         7
Tables          87
Name: Sub-Category, dtype: int64

In [83]:
df_sales.iloc[:50].groupby(['City', 'Sub-Category'])[['Sub-Category','Segment']].count()

                                 Sub-Category  Segment
City               Sub-Category
Arlington          Storage                  1        1
Berlin             Appliances               1        1
                   Phones                   1        1
Brisbane           Phones                   2        2
Bytom              Tables                   1        1
Dakar              Copiers                  1        1
Edinburgh          Appliances               1        1
Gold Coast         Appliances               1        1
Gorakhpur          Phones                   1        1
Gulfport           Furnishings              1        1
Hamilton           Tables                   1        1
Huddersfield       Phones                   1        1
Jamshedpur         Machines                 1        1
Jizan              Phones                   1        1
Juárez             Phones                   1        1
Kabul              Tables                   1        1
Kamina             Phones                   1        1
Leipzig            Appliances               1        1
Los Angeles        Chairs                   1        1
Mataram            Phones                   1        1
Montreuil          Chairs                   1        1
Mudanjiang         Appliances               1        1
New York City      Accessories              1        1
Oklahoma City      Bookcases                1        1
                   Phones                   1        1
Paris              Appliances               1        1
Paysandú           Chairs                   1        1
Porirua            Chairs                   1        1
Prato              Appliances               1        1
Saint-Brieuc       Machines                 1        1
San Francisco      Phones                   1        1
                   Storage                  1        1
Santo Domingo      Phones                   1        1
Seattle            Art                      1        1
                   Chairs                   1        1
                   Storage                  1        1
Shouguang          Chairs                   1        1
Soyapango          Tables                   1        1
Stockton-on-Tees   Copiers                  1        1
Surat              Chairs                   1        1
Suzhou             Chairs                   1        1
Sydney             Phones                   1        1
Taipei             Tables                   1        1
Thiruvananthapuram Bookcases                1        1
Toledo             Chairs                   1        1
Townsville         Copiers                  1        1
Troy               Fasteners                1        1
Uvinza             Appliances               1        1
Wollongong         Chairs                   1        1

HOMEWORK

- If there are two DataFrames, how you can join them together
- Combining DataFrames with `merge` and `concat`

### Temporal Data - OPTIONAL

In [36]:
from datetime import datetime

# -------------------------------
# 1. Creating a datetime column
# -------------------------------
# Example data with date strings
data = {
    'event': ['Start', 'Middle', 'End'],
    'date_str': ['2024-01-15', '2024-05-20', '2024-12-31']
}

df = pd.DataFrame(data)

In [37]:
# Convert string to datetime
df['date'] = pd.to_datetime(df['date_str'], format='%Y-%m-%d', errors='coerce')

df.dtypes

event                  str
date_str               str
date        datetime64[us]
dtype: object

In [38]:
# -------------------------------
# 2. Extracting date components
# -------------------------------
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.day_name()

In [39]:
# -------------------------------
# 3. Filtering by date range
# -------------------------------
start_date = '2024-05-01'
end_date = '2024-12-31'
mask = (df['date'] >= start_date) & (df['date'] <= end_date)
filtered_df = df.loc[mask]

In [40]:
# -------------------------------
# 4. Current date & time
# -------------------------------
now = pd.Timestamp.now()
today = pd.Timestamp.today()
print("Current Timestamp:", now)
print("Today's Date:", today.date())
print(today)
print("Today's Date:", today.date())

Current Timestamp: 2026-04-08 12:52:56.630831
Today's Date: 2026-04-08
2026-04-08 12:52:56.630975
Today's Date: 2026-04-08

In [41]:
# -------------------------------
# 5. Date arithmetic
# -------------------------------
df['date_plus_7_days'] = df['date'] + pd.Timedelta(days=7)
df['days_since_event'] = (today - df['date']).dt.days