### Duplicates
- Exact Duplicates
    - every single column in a row A is idential to row B
- Partial Duplicates
    - only specific columns match

In [1]:
# Sample dataset of e-commerce transactions
# Create a dictionary of multiple data items
data = [
    {"Transaction ID": 1001, "Customer Name": "Alice Smith",    "Email": "alice@example.com",         "Product": "Laptop", "Quantity": 1,     "Price": 1200.00, "Purchase Date": "2024-09-15", "Delivery Status": True},
    {"Transaction ID": 1002, "Customer Name": "Bob Jones",       "Email": None,                       "Product": "Headphones", "Quantity": 2, "Price": 150.00, "Purchase Date": "2024-09-16", "Delivery Status": True},
    {"Transaction ID": 1003, "Customer Name": "Charlie Johnson", "Email": "charlie#example.com",       "Product": "Smartphone", "Quantity": 5, "Price": 800.00, "Purchase Date": "16/09/2024", "Delivery Status": True},
    {"Transaction ID": 1004, "Customer Name": "David Lee",       "Email": "david.lee@example.com",    "Product": "Laptop", "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-17", "Delivery Status": False},
    {"Transaction ID": 1005, "Customer Name": "Eve Martinez",    "Email": "eve.martinez@example.com", "Product": "Smartwatch", "Quantity": 2,"Price": None, "Purchase Date": "17th Sep 2024", "Delivery Status": True},
    {"Transaction ID": 1006, "Customer Name": "Frank Wright",    "Email": None,                       "Product": "Tablet", "Quantity": None, "Price": 600.00, "Purchase Date": "2024-09-18", "Delivery Status": False},
    {"Transaction ID": 1007, "Customer Name": 23,                "Email": "grace.lee@example.com",   "Product": "Laptop", "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-19", "Delivery Status": True},
    {"Transaction ID": 1008, "Customer Name": "Hank Brown",      "Email": "hank.brown@example.com",   "Product": "Monitor", "Quantity": 2,   "Price": 300.00, "Purchase Date": "09/19/2024", "Delivery Status": True},
    {"Transaction ID": 1009, "Customer Name": "Ivy Thompson",    "Email": None,                        "Product": "Keyboard", "Quantity": 2, "Price": 100.00, "Purchase Date": "2024/09/20", "Delivery Status": False},
    {"Transaction ID": 1010, "Customer Name": "Jack Davis",      "Email": "jack@example.com",         "Product": "Mouse", "Quantity": 1,     "Price": 50.00, "Purchase Date": "2024-09-21", "Delivery Status": True},
    {"Transaction ID": 1005, "Customer Name": "Eve Martinez",    "Email": "eve.martinez@example.com", "Product": "Smartwatch", "Quantity": 2,"Price": None, "Purchase Date": "17th Sep 2024", "Delivery Status": True}, # Duplicate entry
    {"Transaction ID": 1011, "Customer Name": "Alice Smith",    "Email": "alice@example.com",         "Product": "Laptop", "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-15", "Delivery Status": True},  
    {"Transaction ID": 1012, "Customer Name": "Kurt Evans",     "Email": "kurt.evans@example.com",     "Product": "Smartwatch","Quantity": -1,"Price": 200.00, "Purchase Date": "2024-09-22", "Delivery Status": True},  # Outlier quantity
    {"Transaction ID": 1013, "Customer Name": "Liam Adams",     "Email": "liam.adams@example.com",    "Product": "Headphones", "Quantity": 2, "Price": 150.00, "Purchase Date": "2024-09-23", "Delivery Status": False},
    {"Transaction ID": 1014, "Customer Name": "Mia Clark",       "Email": "mia.clark@example.com",     "Product": None, "Quantity": 1,        "Price": 0,      "Purchase Date": "2024-09-24", "Delivery Status": True},  # Price anomaly
    {"Transaction ID": 1005, "Customer Name": "Eve Martinez",    "Email": "eve.martinez@example.com", "Product": "Smartwatch", "Quantity": 2,"Price": None, "Purchase Date": "17th Sep 2024", "Delivery Status": True}, # Duplicate entry    {"Transaction ID": 1015, "Customer Name": "Nina Turner",     "Email": None,                         "Product": "Tablet", "Quantity": 1,     "Price": 600.00, "Purchase Date": "24-09-2024", "Delivery Status": True},
    {"Transaction ID": 1016, "Customer Name": "Oscar Harris",    "Email": "oscar.harris@example.com",  "Product": "Laptop", "Quantity": 2,    "Price": 1200.00, "Purchase Date": "2024-09-25", "Delivery Status": True},
    {"Transaction ID": 1017, "Customer Name": "Paul Young",     "Email": "paulyoung",                  "Product": "Monitor", "Quantity": 2,   "Price": 300.00, "Purchase Date": "09/25/2024", "Delivery Status": True},
    {"Transaction ID": 1018, "Customer Name": "Quinn Lopez",    "Email": None,                         "Product": "Smartphone", "Quantity": 1,"Price": 800.00, "Purchase Date": "2024-09-26", "Delivery Status": False},
    {"Transaction ID": 1019, "Customer Name": "Rachel Scott",    "Email": "rachel.scott@example.com",  "Product": "Keyboard", "Quantity": 2,  "Price": 100.00, "Purchase Date": "2024-09-27", "Delivery Status": True},
    {"Transaction ID": 1020, "Customer Name": "Steve King",     "Email": "steve.king@example.com",     "Product": "Mouse", "Quantity": None,  "Price": 50.00, "Purchase Date": "2024-09-28", "Delivery Status": True},
]

# Displaying the dataset
import pandas as pd

# Convert the list of dictionaries to a DataFrame for easier visualization and manipulation
df = pd.DataFrame(data)
df.head()

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,17th Sep 2024,True

In [ ]:
# check for duplicates

df.duplicated().sum() # duplicate rows/records

np.int64(2)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   21 non-null     int64
 1   Customer Name    21 non-null     object
 2   Email            17 non-null     str
 3   Product          20 non-null     str
 4   Quantity         19 non-null     float64
 5   Price            18 non-null     float64
 6   Purchase Date    21 non-null     str
 7   Delivery Status  21 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 1.3+ KB

In [ ]:
# Exact Duplicate Removal

df_clean = df.drop_duplicates( ) # inplace = True
df_clean.info()
df_clean.duplicated().sum()

<class 'pandas.DataFrame'>
Index: 19 entries, 0 to 20
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   19 non-null     int64
 1   Customer Name    19 non-null     object
 2   Email            15 non-null     str
 3   Product          18 non-null     str
 4   Quantity         17 non-null     float64
 5   Price            18 non-null     float64
 6   Purchase Date    19 non-null     str
 7   Delivery Status  19 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 1.2+ KB

np.int64(0)

In [10]:
# check for partial duplicates -----

df.Email.duplicated().sum()

df_clean.drop_duplicates(subset= ['Email'],
                         inplace= True, # modifies original
                         keep= 'first' # which one of the duplicates to keep
                         )

In [13]:
df_clean

df_clean.reset_index()
df_clean.reset_index(drop= True) # it will not record the previous indicies in a new column

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,17th Sep 2024,True
5,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
6,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
7,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
8,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
9,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
10,1014,Mia Clark,mia.clark@example.com,NaN,1.0,0.0,2024-09-24,True
11,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
12,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
13,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
14,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

### Some Other Types of Errors
-

In [15]:
df['Purchase Date']

0        2024-09-15
1        2024-09-16
2        16/09/2024
3        2024-09-17
4     17th Sep 2024
5        2024-09-18
6        2024-09-19
7        09/19/2024
8        2024/09/20
9        2024-09-21
10    17th Sep 2024
11       2024-09-15
12       2024-09-22
13       2024-09-23
14       2024-09-24
15    17th Sep 2024
16       2024-09-25
17       09/25/2024
18       2024-09-26
19       2024-09-27
20       2024-09-28
Name: Purchase Date, dtype: str

In [18]:
pd.to_datetime(df['Purchase Date'], format= 'mixed', errors= 'coerce')

0    2024-09-15
1    2024-09-16
2    2024-09-16
3    2024-09-17
4    2024-09-17
5    2024-09-18
6    2024-09-19
7    2024-09-19
8    2024-09-20
9    2024-09-21
10   2024-09-17
11   2024-09-15
12   2024-09-22
13   2024-09-23
14   2024-09-24
15   2024-09-17
16   2024-09-25
17   2024-09-25
18   2024-09-26
19   2024-09-27
20   2024-09-28
Name: Purchase Date, dtype: datetime64[us]

In [20]:
df['Purchase Date'] = pd.to_datetime(df['Purchase Date'], format= 'mixed', errors= 'coerce')
df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,2024-09-16,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,2024-09-17,True
5,1006,Frank Wright,NaN,Tablet,NaN,600.0,2024-09-18,False
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,2024-09-19,True
8,1009,Ivy Thompson,NaN,Keyboard,2.0,100.0,2024-09-20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,2024-09-17,True
11,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
12,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
13,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
14,1014,Mia Clark,mia.clark@example.com,NaN,1.0,0.0,2024-09-24,True
15,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,2024-09-17,True
16,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
17,1017,Paul Young,paulyoung,Monitor,2.0,300.0,2024-09-25,True
18,1018,Quinn Lopez,NaN,Smartphone,1.0,800.0,2024-09-26,False
19,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [ ]:
name = df['Email'][6].split("@")[0].replace('.', " ").title()

df.loc[6, 'Customer Name'] = name

In [39]:
df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,2024-09-16,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,2024-09-17,True
5,1006,Frank Wright,NaN,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,2024-09-19,True
8,1009,Ivy Thompson,NaN,Keyboard,2.0,100.0,2024-09-20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,2024-09-17,True
11,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
12,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
13,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
14,1014,Mia Clark,mia.clark@example.com,NaN,1.0,0.0,2024-09-24,True
15,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,2024-09-17,True
16,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
17,1017,Paul Young,paulyoung,Monitor,2.0,300.0,2024-09-25,True
18,1018,Quinn Lopez,NaN,Smartphone,1.0,800.0,2024-09-26,False
19,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

### Homework Exercise:
- Clean 3 real life datasets
    - have in the REPO

### Exercise [Optional]
- take the first name
- use the first name to impute all the emails correctly

In [ ]:
df['Customer Name']

0         Alice Smith
1           Bob Jones
2     Charlie Johnson
3           David Lee
4        Eve Martinez
5        Frank Wright
6                  23
7          Hank Brown
8        Ivy Thompson
9          Jack Davis
10        Alice Smith
11         Kurt Evans
12         Liam Adams
14        Nina Turner
15       Oscar Harris
16         Paul Young
17        Quinn Lopez
18       Rachel Scott
19         Steve King
Name: Customer Name, dtype: object

In [ ]:
df['Customer Name'][0].split()[0].lower() + '@email.com' # ---> Email

'alice@email.com'