# $$Data-Cleaning$$

- Data in real life is very messy
- This mess:
    - missing values
    - duplicates
    - Outliers
    - 
    - 
    - errors - Typos
    - unnecessary indentation, punctuation, syntax garbage
        - eg. XML data from websites
        - contains a lot of < adfaf: <  adfasd : dfd >>
        - extra < / == or >
    - important for data science, analytics, as well as Machine Learning

Some terminology related to Data:
- **Transformation** - we apply mathematical operataions to change the distribution or scale of data
    - Data distribution or data scale
    
- **Normalization** - we adjust the values to a common scale without distorting the range - so that no features of data dominate the others due to scale
    - when we want our data to have bounds - upper and lower
    - Range = 0 to 1

- **Standardization** - convert data into a standard form 
    - rescale the features such that the mean comes out to be zero

willingness to stay at company - Salary and years of experience
- salary - experience
- 50  - 1
- 100 - 2
- 150 - 3
- 
- 50/5  - 1
- 100/5 - 2
- 150/5 - 3

For the company, what makes more sense?
- should they keep an employee with such a high salary?
- or do they need an employee with such experience
- 
- What will the company prefer?
- which of the two is the more important feature
- 
- computers look at numbers - if a computer has to make a decision
    - what will the computer think of as more important?
    - what does the coomputer see? numbers. larger the number. more the importance.
    -

#### Data Ingestion
- bring in data

```python
df = pd.read_csv
df = pd.read_excel
df = pd.read_json
df = pd.read_parquet
df = pd.read_pickle
df = pd.read_html
df = pd.read_xml

In [1]:
import pandas as pd

df_gdp_us = pd.read_csv('gdp_us_dollars.csv')

# df_gni_us = pd.read_csv('gni_us_dollars.csv')

# df_gni_cp = pd.read_csv('gni_at_current_prices.csv')

In [2]:
# to check some data
df_gdp_us.head()
# df_gdp_us.info()


# unique values in countries
# to see which countries do i have the data for

df_gdp_us.country_or_area.unique()
df_gdp_us.country_or_area.value_counts()

country_or_area
Afghanistan                          46
Albania                              46
Algeria                              46
Andorra                              46
Angola                               46
                                     ..
Yemen: Former Yemen Arab Republic    21
Curaçao                              11
Sint Maarten (Dutch part)            11
South Sudan                           8
Sudan                                 8
Name: count, Length: 220, dtype: int64

In [3]:
# Sample dataset of e-commerce transactions
# Create a dictionary of multiple data items
data = [
    {"Transaction ID": 1001, "Customer Name": "Alice Smith",    "Email": "alice@example.com",           "Product": "Laptop", "Quantity": 1,     "Price": 1200.00, "Purchase Date": "2024-09-15", "Delivery Status": True},
    {"Transaction ID": 1002, "Customer Name": "Bob Jones",       "Email": None,                         "Product": "Headphones", "Quantity": 2, "Price": 150.00, "Purchase Date": "2024-09-16", "Delivery Status": True},
    {"Transaction ID": 1003, "Customer Name": "Charlie Johnson", "Email": "charlie#example.com",         "Product": "Smartphone", "Quantity": 5, "Price": 800.00, "Purchase Date": "16/09/2024", "Delivery Status": True},
    {"Transaction ID": 1004, "Customer Name": "David Lee",       "Email": "david.lee@example.com",      "Product": "Laptop", "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-17", "Delivery Status": False},
    {"Transaction ID": 1005, "Customer Name": "Eve Martinez",    "Email": "eve.martinez@example.com",   "Product": "Smartwatch", "Quantity": 2,"Price": None, "Purchase Date": "17th Sep 2024", "Delivery Status": True},
    {"Transaction ID": 1006, "Customer Name": "Frank Wright",    "Email": None,                         "Product": "Tablet", "Quantity": None, "Price": 600.00, "Purchase Date": "2024-09-18", "Delivery Status": False},
    {"Transaction ID": 1007, "Customer Name": 23,                "Email": "grace.lee@example.com",     "Product": "Laptop", "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-19", "Delivery Status": True},
    {"Transaction ID": 1008, "Customer Name": "Hank Brown",      "Email": "hank.brown@example.com",     "Product": "Monitor", "Quantity": 2,   "Price": 300.00, "Purchase Date": "09/19/2024", "Delivery Status": True},
    {"Transaction ID": 1009, "Customer Name": "Ivy Thompson",    "Email": None,                          "Product": "Keyboard", "Quantity": 2, "Price": 100.00, "Purchase Date": "2024/09/20", "Delivery Status": False},
    {"Transaction ID": 1010, "Customer Name": "Jack Davis",      "Email": "jack@example.com",           "Product": "Mouse", "Quantity": 1,     "Price": 50.00, "Purchase Date": "2024-09-21", "Delivery Status": True},
    {"Transaction ID": 1011, "Customer Name": "Alice Smith",    "Email": "alice@example.com",           "Product": "Laptop", "Quantity": 1,    "Price": 1200.00, "Purchase Date": "2024-09-15", "Delivery Status": True},  # Duplicate entry
    {"Transaction ID": 1012, "Customer Name": "Kurt Evans",     "Email": "kurt.evans@example.com",       "Product": "Smartwatch","Quantity": -1,"Price": 200.00, "Purchase Date": "2024-09-22", "Delivery Status": True},  # Outlier quantity
    {"Transaction ID": 1013, "Customer Name": "Liam Adams",     "Email": "liam.adams@example.com",      "Product": "Headphones", "Quantity": 2, "Price": 150.00, "Purchase Date": "2024-09-23", "Delivery Status": False},
    {"Transaction ID": 1014, "Customer Name": "Mia Clark",       "Email": "mia.clark@example.com",       "Product": None, "Quantity": 1,        "Price": 0,      "Purchase Date": "2024-09-24", "Delivery Status": True},  # Price anomaly
    {"Transaction ID": 1015, "Customer Name": "Nina Turner",     "Email": None,                         "Product": "Tablet", "Quantity": 1,     "Price": 600.00, "Purchase Date": "24-09-2024", "Delivery Status": True},
    {"Transaction ID": 1016, "Customer Name": "Oscar Harris",    "Email": "oscar.harris@example.com",    "Product": "Laptop", "Quantity": 2,    "Price": 1200.00, "Purchase Date": "2024-09-25", "Delivery Status": True},
    {"Transaction ID": 1017, "Customer Name": "Paul Young",     "Email": "paulyoung",                    "Product": "Monitor", "Quantity": 2,   "Price": 300.00, "Purchase Date": "09/25/2024", "Delivery Status": True},
    {"Transaction ID": 1018, "Customer Name": "Quinn Lopez",    "Email": None,                           "Product": "Smartphone", "Quantity": 1,"Price": 800.00, "Purchase Date": "2024-09-26", "Delivery Status": False},
    {"Transaction ID": 1019, "Customer Name": "Rachel Scott",    "Email": "rachel.scott@example.com",    "Product": "Keyboard", "Quantity": 2,  "Price": 100.00, "Purchase Date": "2024-09-27", "Delivery Status": True},
    {"Transaction ID": 1020, "Customer Name": "Steve King",     "Email": "steve.king@example.com",       "Product": "Mouse", "Quantity": None,  "Price": 50.00, "Purchase Date": "2024-09-28", "Delivery Status": True},
]

# Displaying the dataset
import pandas as pd

# Convert the list of dictionaries to a DataFrame for easier visualization and manipulation
df = pd.DataFrame(data)
df.head()

dfcopy = pd.DataFrame(data)

### Exercise
- Basic Exploration of this imported data
- what methods you used - in chat

1. Data Exploration
- df.shape()
- df.dtypes()
- 
- df.head()
- df.tail()
- df.sample()
- df.info()
- df.describe()
- 
- df.isnull().sum()
- df.duplicated().sum()
- 
- df.columnName.unique()
- df.columnName.value_counts()
- 
- df.corr()

In [4]:
df[['Quantity','Price']].corr()

          Quantity     Price
Quantity  1.000000  0.004823
Price     0.004823  1.000000

#### NaN - Missing Values
- Number a Number
    - in pandas are saved as: Numpy Objects
- 
- 

## **Handling Missing Values**

**Deletion - delete Nan values**

1. Listwise - df.dropna()
    - if < 5% missing data

2. Pairwise - df.corr(), .mean(), cov() - get results by just ignoring null values

3. Targetted Dropping row:  df.dropna(subset = [col1, col2, ])
    - when you know about columns that have a lot of missing values

4. Dropping columns: df.drop(columns =  [col1, col2, ])
    - if 60 to 70 % of data is missing from a column

5. Deletion using thresolds:  df.dropna(thresh = , axis = 1)
    - can work on rows or columns and we set the threshold

In [5]:
df.info()
listwise_clean = df.dropna()
listwise_clean.info()

# you delete the entire row where a null value existed
# from 20 we went to 12

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   20 non-null     int64
 1   Customer Name    20 non-null     object
 2   Email            15 non-null     str
 3   Product          19 non-null     str
 4   Quantity         18 non-null     float64
 5   Price            19 non-null     float64
 6   Purchase Date    20 non-null     str
 7   Delivery Status  20 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 1.2+ KB
<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 18
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   12 non-null     int64
 1   Customer Name    12 non-null     object
 2   Email            12 non-null     str
 3   Product          12 non-null     str
 4   Quantity         12 non-null     float64
 5   Price            12 non-null     float64
 6   Purchase Date    12 non-null     str
 7   Delivery Status  12 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 780.0+ bytes

In [6]:
df_listwise = df.copy()
df_listwise.dropna(inplace = True)

df_listwise.info()

df_listwise.isnull().sum()

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 18
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   12 non-null     int64
 1   Customer Name    12 non-null     object
 2   Email            12 non-null     str
 3   Product          12 non-null     str
 4   Quantity         12 non-null     float64
 5   Price            12 non-null     float64
 6   Purchase Date    12 non-null     str
 7   Delivery Status  12 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 780.0+ bytes

Transaction ID     0
Customer Name      0
Email              0
Product            0
Quantity           0
Price              0
Purchase Date      0
Delivery Status    0
dtype: int64

- since we lose a lot of data, this method is not prefered as much
- only use this if, you are loosing < 5% data - Acceptable

In [7]:
# Pairwise   - df.corr(), df.cov()
# save dataframe by implementing a maths op
# automatically ignores any null values -- and gives results

df_numeric = df[['Quantity','Price']]


df_numeric.corr()

df_numeric.mean()

Quantity      1.555556
Price       536.842105
dtype: float64

In [8]:
# Targetted NaN Removal
# very useful

# Target a column, remove any ROWS that have null in that column

df_rowwise = df.dropna(subset= ["Email", 'Product', 'Quantity', 'Price'])
df_rowwise.info()

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 18
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   12 non-null     int64
 1   Customer Name    12 non-null     object
 2   Email            12 non-null     str
 3   Product          12 non-null     str
 4   Quantity         12 non-null     float64
 5   Price            12 non-null     float64
 6   Purchase Date    12 non-null     str
 7   Delivery Status  12 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 780.0+ bytes

In [9]:
# Column Removal --- for problematic columns

df_del_email = df.drop(columns= "Email")

df_del_email.isna().sum()

df_del_email.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   20 non-null     int64
 1   Customer Name    20 non-null     object
 2   Product          19 non-null     str
 3   Quantity         18 non-null     float64
 4   Price            19 non-null     float64
 5   Purchase Date    20 non-null     str
 6   Delivery Status  20 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(2)
memory usage: 1.1+ KB

#### Exercise

- create a new df that only has numerical columns, by deleting rest of the types of columns
    - keep numeric, delete the rest

In [10]:
df_numerical = df.select_dtypes(include = 'number')
df_numerical.head(1)

   Transaction ID  Quantity   Price
0            1001       1.0  1200.0

In [11]:
# column NaN removal based on a ---- threshold
# we focus on non-null values

col_thresh = df.dropna(thresh = 19, axis = 1)
# At least 19 values should be in a column to qualify for this instruction

col_thresh = df.dropna(thresh = df.shape[0] - 5, axis = 1) # df.shape[0] --- number of rows
col_thresh.info()

# rows
row_thresh = df.dropna(thresh = 7, axis = 0) # atleast 7 non null values # 
row_thresh = df.dropna(thresh = df.shape[1] - 1, axis = 0) # df.shape[1] -- number of columns
row_thresh

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   20 non-null     int64
 1   Customer Name    20 non-null     object
 2   Email            15 non-null     str
 3   Product          19 non-null     str
 4   Quantity         18 non-null     float64
 5   Price            19 non-null     float64
 6   Purchase Date    20 non-null     str
 7   Delivery Status  20 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(1), str(3)
memory usage: 1.2+ KB

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,17th Sep 2024,True
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,NaN,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,NaN,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,NaN,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,NaN,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

---

### **IMPUTATION**

- filling the NaN values
- Filling the empty place, or values

- we can either entirely remove the NaN value rows, 
- or we can try to fill some of the NaN values, using various methods
    - with values that make sense in the positions of NaN values
    - eg if we have a columns in which data looks like this:
        - <h3> 10,20,20,20,20,20,20,10,10,20,20,20,20,10,`NaN`,20,20,20,20,20,10,20,20,20</h3>
        - What will you fill the missing value with?
        - Estimate what was originally present in this place?
        - 
        - we can see that the number has to be either 10 or 20
            - that is the pattern
            - we are making a prediction based on the rest of the values
            - 
        - Statistically - `Mode`- the most frequent value 
        - in case we were wrong, it still would not affect the overall data a lot, if there is a lot of data present
        - Distribution of data would not be affected too much

### Numerical Imputation

We use the .fillna() method --- use `inplace = True` to modify original
- Constant - `df.fillna(constant)`
    - we generally use 0 or 1 to fill values
    <!-- - if string columns - use 'Unknown' -->

- Mean - df.column.mean()
    - take average value of a column and fill it in the NaN values

- Median - df.col.median()

- Mode - df.col.mode()
    - The element that is most frequent
        - eg. 1,1,1,2,2,2,2,3,3,3
    - Multiple Mode:
        - more than one modes
        - mode[0] - first mode
        - mode[1]- second mode

In [12]:
series = pd.Series([1,2,3,1,2,2,3,3]) # two times 1, and 2
series.mode()#[1]

0    2
1    3
dtype: int64

In [13]:
df.fillna(1)

mean = df.Price.mean()

df.Price.fillna(mean)


df.Price.fillna(    df.Price.median())

0     1200.0
1      150.0
2      800.0
3     1200.0
4      300.0
5      600.0
6     1200.0
7      300.0
8      100.0
9       50.0
10    1200.0
11     200.0
12     150.0
13       0.0
14     600.0
15    1200.0
16     300.0
17     800.0
18     100.0
19      50.0
Name: Price, dtype: float64

In [14]:
df[['Quantity','Price']].mean()
df[['Quantity','Price']].median()
df[['Quantity','Price']].mode()

   Quantity   Price
0       1.0  1200.0
1       2.0     NaN

In [15]:
# Imputation --- of price with the median price
df['Price'] = df['Price'].fillna( df.Price.median())

In [16]:
# Imputation --- of Quantity with mode
mode_quantity = df.Quantity.mode()[0]
df['Quantity'] = df['Quantity'].fillna(mode_quantity)

In [17]:
# fixing the -1 is also a cleaning process - but it is not imputation
df['Quantity'] = (df['Quantity'] ** 2)**0.5  # square everything, take square root

In [18]:
# Fix Product issues
df.dropna(subset= "Product", inplace = True)

In [19]:
df_clean = df
df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,300.0,17th Sep 2024,True
5,1006,Frank Wright,NaN,Tablet,1.0,600.0,2024-09-18,False
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,NaN,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
14,1015,Nina Turner,NaN,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,NaN,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,1.0,50.0,2024-09-28,True

#### Other Imputation Methods:
- Simple Imputer
    - not as much control as manual cleaning
    - 
- Dictionary Based 
    - Strategic Imputation
    - you can have control of what to do on which column

In [20]:
# pip install scikit-learn

In [21]:
numdf = dfcopy[['Quantity', 'Price']]
numdf

    Quantity   Price
0        1.0  1200.0
1        2.0   150.0
2        5.0   800.0
3        1.0  1200.0
4        2.0     NaN
5        NaN   600.0
6        1.0  1200.0
7        2.0   300.0
8        2.0   100.0
9        1.0    50.0
10       1.0  1200.0
11      -1.0   200.0
12       2.0   150.0
13       1.0     0.0
14       1.0   600.0
15       2.0  1200.0
16       2.0   300.0
17       1.0   800.0
18       2.0   100.0
19       NaN    50.0

In [22]:
# imputer object using sklearn
# imputer use it to fill values in the dataframe

from sklearn.impute import SimpleImputer

imputerrr = SimpleImputer(strategy= 'median') # simple imputer can change strategy

numdf = imputerrr.fit_transform(numdf)
numdf = pd.DataFrame(numdf)
numdf

      0       1
0   1.0  1200.0
1   2.0   150.0
2   5.0   800.0
3   1.0  1200.0
4   2.0   300.0
5   1.5   600.0
6   1.0  1200.0
7   2.0   300.0
8   2.0   100.0
9   1.0    50.0
10  1.0  1200.0
11 -1.0   200.0
12  2.0   150.0
13  1.0     0.0
14  1.0   600.0
15  2.0  1200.0
16  2.0   300.0
17  1.0   800.0
18  2.0   100.0
19  1.5    50.0

In [23]:
# Dictionary Based Fill
imputation_values = {
    'Price' : df.Price.median().round(0),
    'Quantity' : df.Quantity.mode()[0],
    'Product' : df.Product.mode()[0]
}

In [24]:
df = dfcopy # put dfcopy values back to df

df_filled = df.fillna(value = imputation_values)
df_filled

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,300.0,17th Sep 2024,True
5,1006,Frank Wright,NaN,Tablet,1.0,600.0,2024-09-18,False
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,NaN,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,Laptop,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,NaN,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,NaN,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,1.0,50.0,2024-09-28,True

In [28]:
df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,NaN,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,NaN,Tablet,NaN,600.0,2024-09-18,False
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,NaN,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,NaN,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,NaN,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,NaN,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [ ]:
# forward fill   ---- uses previous values
forward_filled_df = df.ffill()
forward_filled_df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,alice@example.com,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,1200.0,17th Sep 2024,True
5,1006,Frank Wright,eve.martinez@example.com,Tablet,2.0,600.0,2024-09-18,False
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,hank.brown@example.com,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,Headphones,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,mia.clark@example.com,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,paulyoung,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,2.0,50.0,2024-09-28,True

In [31]:
# backward fill   ---- uses next values
backward_filled_df = df.bfill()
backward_filled_df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,charlie#example.com,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,5.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,2.0,600.0,17th Sep 2024,True
5,1006,Frank Wright,grace.lee@example.com,Tablet,1.0,600.0,2024-09-18,False
6,1007,23,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,jack@example.com,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,1.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,Tablet,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,oscar.harris@example.com,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,rachel.scott@example.com,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [26]:
df.Email.fillna("unknown", inplace= True)

C:\Users\devid\AppData\Local\Temp\ipykernel_4504\3459292242.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.Email.fillna("unknown", inplace= True)

0            alice@example.com
1                      unknown
2          charlie#example.com
3        david.lee@example.com
4     eve.martinez@example.com
5                      unknown
6        grace.lee@example.com
7       hank.brown@example.com
8                      unknown
9             jack@example.com
10           alice@example.com
11      kurt.evans@example.com
12      liam.adams@example.com
13       mia.clark@example.com
14                     unknown
15    oscar.harris@example.com
16                   paulyoung
17                     unknown
18    rachel.scott@example.com
19      steve.king@example.com
Name: Email, dtype: str